# Generated by Django 4.2.1 on 2023-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PT', 'Pets'), ('E', 'Eggs'), ('OR', 'Other'), ('ML', 'Milk'), ('FZ', 'Fertilizers'), ('CP', 'Crops'), ('FR', 'Fruits'), ('V', 'Vegitables'), ('FS', 'Fish'), ('T', 'Tubers'), ('SP', 'Spices'), ('SD', 'Seeds')], max_length=2),
        ),
    ]
