# Generated by Django 4.2.2 on 2023-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('T', 'Tubers'), ('SD', 'Seeds'), ('V', 'Vegitables'), ('E', 'Eggs'), ('CP', 'Crops'), ('FR', 'Fruits'), ('FS', 'Fish'), ('FZ', 'Fertilizers'), ('PT', 'Pets'), ('SP', 'Spices'), ('OR', 'Other')], max_length=2),
        ),
    ]
